### ISSUE TITLE
using this plugin makes the android build fail

### ISSUE THREAD

**Issue by Shovaleliezer** [kulichin/UnrealFirebaseAuthentication#1]
Error:   ERROR: cmd.exe failed with args /c "D:\games\CaptainCoinTest\Intermediate\Android\gradle\rungradle.bat" :app:bundleDebug
when the plugin disabled the build works, and suggetions?

**Comment by kulichin** [comment]
Can you provide a complete log?

**Comment by Shovaleliezer** [comment]
![image](https://user-images.githubusercontent.com/46319026/132977346-c88d0e9c-7860-4b05-8f79-fbbbba620162.png)

**Comment by Shovaleliezer** [comment]
sorry for the half screen shot, anyway when the plugin is off the packaging is working and when your plugin is enabled it gives me this error, i followed your doc and did everything :) thanks for responding

**Comment by kulichin** [comment]
Have you added google-services.json to your 
 {ProjectName}\Build\Android\ directory?

**Comment by Shovaleliezer** [comment]
![image](https://user-images.githubusercontent.com/46319026/132986063-6516050d-54ab-4e35-82ff-8d66dd54d7bf.png)

**Comment by Shovaleliezer** [comment]
yep, should i set anything in ue4 settings? i put the facebook id in your plugin(project settings)

**Comment by kulichin** [comment]
Ok, then try deleting the 'Intermediate' and 'Saved' folders and rebuild the project, maybe this will help.

**Comment by Shovaleliezer** [comment]
tried, no success :(

**Comment by kulichin** [comment]
I didn't see the 'google-services' file extension on your screenshot. Are you sure that 'google-services' file has '.json' extension?

**Comment by Shovaleliezer** [comment]
you can see in the type Json File, can you show me how it looks in yours?

**Comment by kulichin** [comment]
Yes, the problem occurs when you are trying to build a plugin from marketplace. Currently I have fixed a bug in the repo, later the fix will appear in the Marketplace.
